[project]
name = "benkyou-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.6.10",
    "django>=5.1.4",
    "mypy>=1.14.1",
    "psycopg>=3.2.3",
    "ruff>=0.8.5",
    "selenium>=4.27.1",
]

[tool.mypy]
exclude = "main/migrations"
follow_untyped_imports = true
strict = true
untyped_calls_exclude = ["django"]
