# Generated by Django 5.1.4 on 2025-04-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_is_verified",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
