# Generated by Django 5.2 on 2025-06-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_user_email_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
