on:
  push:
    branches:
      - '**'

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format -q --check"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check -q --output-format=concise"

  type-check:
    env:
      ALLOWED_HOSTS:
      CACHE_HOST:
      CACHE_PORT:
      CACHE_SCHEME:
      CELERY_BROKER_HOST:
      CELERY_BROKER_PASSWORD:
      CELERY_BROKER_PORT:
      CELERY_BROKER_SCHEME:
      CELERY_BROKER_USER:
      DATABASE_DB:
      DATABASE_HOST:
      DATABASE_PASSWORD:
      DATABASE_USER:
      DEBUG:
      EMAIL_HOST:
      EMAIL_HOST_USER:
      EMAIL_PORT:
      SECRET_KEY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --all-groups
      - run: uv run mypy .

  test:
    env:
      ALLOWED_HOSTS: localhost
      CACHE_HOST: localhost
      CACHE_PORT: 6379
      CACHE_SCHEME: redis
      CELERY_BROKER_HOST:
      CELERY_BROKER_PASSWORD:
      CELERY_BROKER_PORT:
      CELERY_BROKER_SCHEME: amqp
      CELERY_BROKER_USER:
      DATABASE_DB: postgres
      DATABASE_HOST: localhost
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_USER: postgres
      DEBUG: true
      EMAIL_HOST:
      EMAIL_HOST_USER:
      EMAIL_PORT:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-start-interval 1s
          --health-start-period 5s
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --no-dev --group test
      - run: uv run coverage run --source=main manage.py test --failfast
      - run: uv run coverage report --fail-under 100
