on:
  push:
    branches:
      - '**'

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format -q --check"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check -q --output-format=concise"

  type-check:
    env:
      DATABASE_DB:
      DATABASE_HOST:
      DATABASE_PASSWORD:
      DATABASE_USER:
      DJANGO_ALLOWED_HOSTS: localhost
      DJANGO_DEBUG: false
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --all-groups
      - run: uv run mypy .

  test:
    env:
      DATABASE_DB:
      DATABASE_HOST:
      DATABASE_PASSWORD:
      DATABASE_USER:
      DJANGO_ALLOWED_HOSTS: localhost
      DJANGO_DEBUG: false
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --no-dev --group test
      - run: uv run coverage run --source=main manage.py test --failfast
      - run: uv run coverage report --fail-under 100
