on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: LC_CTYPE=C tr -dc [:alnum:] < /dev/urandom | head -c 50 > django_secret_key
      - run: LC_CTYPE=C tr -dc [:alnum:] < /dev/urandom | head -c 20 > postgres_password
      - run: docker compose pull
      - run: docker compose build
      - run: docker compose run --no-deps --rm app sh -c "ruff check --select A --diff"
      - run: docker compose run --no-deps --rm app sh -c "ruff format --diff"
      - run: docker compose run --rm app sh -c "python manage.py test"
      - if: ${{ always() }}
        run: docker compose down
