on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action
        with:
          push: true
          tags: ghcr.io/kinoubenkyou/benkyou-django
#      - run: docker compose pull
#      - run: docker compose build
#      - run: docker compose push
#      - run: LC_CTYPE=C tr -dc [:alnum:] < /dev/urandom | head -c 50 > django_secret_key
#      - run: LC_CTYPE=C tr -dc [:alnum:] < /dev/urandom | head -c 20 > postgres_password
#      - run: docker compose run --no-deps --rm app sh -c "ruff check --diff"
#      - run: docker compose run --no-deps --rm app sh -c "ruff format --diff"
#      - run: docker compose run --rm app sh -c "python manage.py test --failfast"
#      - if: ${{ always() }}
#        run: docker compose down
