on: [push]
jobs:

  build:
#    permissions:
#      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
      - uses: docker/build-push-action@v6
        with:
#          push: true
          tags: ghcr.io/kinoubenkyou/benkyou-django
          cache-from: type=registry,ref=ghcr.io/kinoubenkyou/benkyou-django:build-cache
          cache-to: type=registry,ref=ghcr.io/kinoubenkyou/benkyou-django:build-cache

#  test:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          password: ${{ secrets.GITHUB_TOKEN }}
#          username: ${{ github.repository_owner }}
#      - uses: docker/metadata-action@v5
#        with:
#          images: ghcr.io/kinoubenkyou/benkyou-django
#      - uses: actions/checkout@v4
#      - run: LC_CTYPE=C tr -dc [:alnum:] < /dev/urandom | head -c 50 > django_secret_key
#      - run: LC_CTYPE=C tr -dc [:alnum:] < /dev/urandom | head -c 20 > postgres_password
#      - run: docker compose run --no-deps --rm app sh -c "ruff check --diff"
#      - run: docker compose run --no-deps --rm app sh -c "ruff format --diff"
#      - run: docker compose run --rm app sh -c "python manage.py test --failfast"
#      - if: ${{ always() }}
#        run: docker compose down
